format:
  html:
    page-layout: full

project:
  type: website
  output-dir: docs

website:
  title: "Svitlo Calculus Course"
  sidebar:
     style: "docked"
     contents:
       - text: "Home"
         href: Introduction.ipynb
       - section: "Lessons"
         contents:
           - text: "Lesson 1"
             href: Lesson 1.ipynb
           - text: "Lesson 2"
             href: Lesson 2.ipynb
           - text: "Lesson 3"
             href: Lesson 3.ipynb
           - text: "Lesson 4"
             href: Lesson 4.ipynb
           - text: "Lesson 5"
             href: Lesson 5.ipynb